            CLS
            SOUND 500, 5
            SOUND 400, 5
            SOUND 500, 5
            SOUND 400, 5
            SOUND 500, 5
            SOUND 400, 5
            SOUND 300, 5
            COLOR 22
            PRINT "***AGE TESTER***"
            COLOR 14
            PRINT " Made by MUKTO"
            COLOR 2
            PRINT "Hello :) How are you today? Please enter your"
            INPUT "age", age
            SOUND 1000, 5
            IF age < 7 THEN PRINT "You are a small child! :() "
            IF age >= 7 THEN PRINT "You are a kid! :) "
            IF age >= 10 THEN PRINT "You are a tween! :) "
            IF age >= 13 THEN PRINT "You are a teenager! ;) "
            IF age >= 18 THEN PRINT "You are an adult! ;) "
            IF age >= 40 THEN PRINT "You are too old! :( "

