            CLS
            SCREEN 13
            CIRCLE (160, 100), 20
            PAINT (160, 100), 15
            COLOR
            PRINT "***AGE TESTER***"
            COLOR 14
            PRINT " Made by MUKTO"
            COLOR 4
            PRINT "Hello :) How are you today? Please enter your"
            INPUT "age", age
            IF age < 7 THEN PRINT "You are a small child! :() "
            IF age >= 7 THEN PRINT "You are a kid! :) "
            IF age >= 10 THEN PRINT "You are a tween! :) "
            IF age >= 13 THEN PRINT "You are a teenager! ;) "
            IF age >= 18 THEN PRINT "You are an adult! ;) "
            IF age >= 40 THEN PRINT "You are too old! :( "

