CLS
PRINT "FREE FALLIN' "
COLOR 4
PRINT "Made by As39002"
PRINT "-------------------"
PRINT
PRINT
COLOR 3
PRINT "LOAD => FileBasis(1)/Documents/QB"
COLOR 4
PRINT
PRINT "Just press Enter to move right"
COLOR 10
SOUND 400, 3

scr.0:
CLS
plr = x + y + z
LET x = 200
LET y = 225
LET z = 250

plr.model:
plr.1 = LINE(200 + x, 200 - x)-(300 - y, 300 + y)-(250 + z, 250 - z),B













