CLS
SCREEN 13
PRINT
COLOR 12
PRINT "***Info bits***"
COLOR 2
PRINT "made by Mukto"
PRINT "info from 'Ask me Anything' book"
COLOR 10
PRINT
COLOR 15
PRINT
INPUT "type any questions for an answer", ans$
SOUND 500, 5
SOUND 900, 5
SOUND 400, 5
SOUND 800, 5
SOUND 300, 5
SOUND 700, 5
IF ans$ = "How old is the universe?" THEN PRINT "The universe is about 13.7 billion years old."
IF ans$ = "How many galaxies are there in the universe?" THEN PRINT "We dont know."

